# Generated by Django 5.2.4 on 2025-07-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='community',
        ),
        migrations.AddField(
            model_name='project',
            name='communities',
            field=models.ManyToManyField(related_name='projects', to='communities.community'),
        ),
    ]
