# Generated by Django 5.2.4 on 2025-07-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        ('core', '0003_userprofile_student_id'),
        ('projects', '0002_remove_project_community_project_communities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='communities',
            field=models.ManyToManyField(blank=True, related_name='projects', to='communities.community'),
        ),
        migrations.AlterField(
            model_name='project',
            name='study_fields',
            field=models.ManyToManyField(blank=True, related_name='projects', to='core.studyfield'),
        ),
        migrations.AlterField(
            model_name='project',
            name='universities',
            field=models.ManyToManyField(blank=True, related_name='projects', to='core.university'),
        ),
    ]
