# Generated by Django 5.2.4 on 2025-07-18 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='code',
            field=models.CharField(blank=True, help_text='SAML organization code (e.g., tudelft.nl)', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='university',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
