# Generated by Django 5.2.4 on 2025-07-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_university_code_university_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='student_id',
            field=models.CharField(blank=True, help_text='Student ID from university', max_length=50, null=True),
        ),
    ]
